receivers:
  otlp:
    protocols:
      grpc:
        endpoint: aws-collector:4317
      http:
        endpoint: aws-collector:4318

processors:
  batch:

exporters:
  awsxray:
    region: us-east-1
  debug:
    verbosity: detailed


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
